routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WebsiteController@index');

Route::post('/login', 'Auth\LoginController@login');

Auth::routes();

//Admin Route
Route::group(['prefix' => 'taskman', 'middleware' => 'auth'], function(){
    Route::post('users/registerFcmToken', 'Admin\DashboardController@registerFcmToken');

    Route::get('dashboard', 'Admin\DashboardController@index')->name('home');
    Route::get('media/image/{id}/delete', 'Admin\DashboardController@taskImageDelete');


    Route::get('work-list', 'Admin\WorkController@workList');
    Route::get('work/create/{task_id}', 'Admin\WorkController@create');
    Route::resource('work', 'Admin\WorkController');
    Route::post('work/sortable', 'Admin\WorkController@sortable');
    // review
    Route::resource('review', 'Admin\ReviewController');
    Route::post('review/update/{id}', 'Admin\ReviewController@update');

    //Late report
    Route::get('emp-late-report/list', 'Admin\LateReportController@empReportList')->name('emp.list');
    Route::get('emp-monthly-late-report', 'Admin\LateReportController@empMonthlyReportList')->name('emp-late-report.monthly');
    //Leave Application
    Route::resource('leave-application', 'Admin\LeaveApplicationController');

    Route::group(['middleware' => 'management' || 'admin'], function(){
        Route::resource('user', 'Admin\UserController');
        Route::post('update-password/{id}', 'Admin\UserController@updatePassword')->name('user.update-password');
        Route::post('user/sortable', 'Admin\UserController@sortable');
        Route::post('user/reset-password/{id}', 'Admin\UserController@resetPassword');
        Route::post('user/reset-email/{id}', 'Admin\UserController@resetEmail');

        Route::resource('project', 'Admin\ProjectController');
        Route::post('user/project', 'Admin\ProjectController@sortable');

        Route::resource('task', 'Admin\TaskController');
        Route::post('task/sortable', 'Admin\TaskController@sortable');

        //Late report
        Route::get('late-report/list', 'Admin\LateReportController@reportList')->name('late_report.list');
        Route::get('monthly-late-report', 'Admin\LateReportController@monthlyReportList')->name('late-report.monthly');
        Route::get('late-report/filter', 'Admin\LateReportController@filter');
        Route::resource('late-report', 'Admin\LateReportController');

        //Leave
        Route::post('/leave/update', 'Admin\LeaveController@leaveUpdate');
        Route::get('/yearly-leave-report', 'Admin\LeaveController@yearlyLeaveReport');
        Route::resource('leave', 'Admin\LeaveController');

        //Application
        Route::get('casualToSick/{id}', 'Admin\LeaveApplicationController@casualToSick');
        Route::get('sickToCasual/{id}', 'Admin\LeaveApplicationController@sickToCasual');

        Route::get('emp-application', 'Admin\LeaveApplicationController@empApplication')->name('emp.application');
        Route::get('/application/approve/{id}', 'Admin\LeaveApplicationController@applicationApprove');
        Route::get('/application/reject/{id}', 'Admin\LeaveApplicationController@applicationReject');
        Route::resource('application', 'Admin\LeaveApplicationController');
        Route::resource('leave-template', 'Admin\LeaveTemplateController');


        Route::resource('emp-note', 'Admin\EmployeeNoteController');

        //Salary Report
        Route::get('/salary', 'Admin\SalaryController@index');
        Route::get('/year-end-salary', 'Admin\SalaryController@yearEnd');


        //Questionnaire
        Route::resource('/exam', 'Admin\ExamController');
        Route::get('/exam/questions/{exam_id}', 'Admin\ExamController@showQuestions')->name('exam.questions');
        Route::get('/exam/examine/{exam_id}', 'Admin\ExamController@showExamine')->name('exam.show-examine'); // Show Examine List along with Exam ID
        Route::post('/exam/change-activity/{id}', 'Admin\ExamController@changeActivity')->name('exam.change-activity');
        Route::resource('/question', 'Admin\ExamQuestionController');
        Route::post('/question/delete-image/{question}', 'Admin\ExamQuestionController@deleteImage');

        //Admin
        Route::resource('/applicant', 'Admin\ApplicantController');
        Route::get('/applicant/remark_show/{id}', 'Admin\ApplicantController@remark');

        // Exam Answers
        Route::get('/exam/answer/{applicant_id}', 'Admin\ExamAnswerController@showAnswers')->name('exam-answer.show');

    });

});

// This is a test route
Route::get('/interview-email', function (){
    $applicant = \App\Models\Applicant::first();
    return view('admin.exam.email', compact('applicant'));
});
// End of test route

Route::get('/interview-exam/{exam_slug}', 'Admin\ApplicantAnswerController@show')->name('interview-exam.show');
Route::post('/interview-exam/submit/{exam_id}', 'Admin\ApplicantAnswerController@submitAnswer')->name('interview-exam.submit');

resources/views/admin/emp-note/_form.blade.php
<div class="col-lg-7 col-md-7 col-xs-12">
    <div class="form-group">
        <h5>Select Users<span class="text-danger">*</span></h5>
        <div class="controls">
            <select class="form-control{{ $errors->has('user_id') ? ' is-invalid' : '' }}" name="user_id">
                <option>-- Select Users --</option>
                @if(!empty($users))
                    @foreach($users as $user)
                        <option value="{{ $user->id }}" {{ isset($data) && $data->user_id == $user->id ? 'selected':'' }}>{{ $user->name }}</option>
                    @endforeach
                @endif
            </select>
            @if ($errors->has('user_id'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('user_id') }}</strong>
                </span>
            @endif
        </div>
    </div>
</div>

<div class="col-lg-7 col-md-7 col-xs-12">
    <div class="form-group">
        <h5>Date<span class="text-danger">*</span></h5>
        <div class="controls">
            <input type="text" name="date" value="{!! old('date', isset($data) ? $data->date:date('Y-m-d')) !!}" class="form-control{{ $errors->has('date') ? ' is-invalid' : '' }} datepicker-autoclose" required data-validation-required-message="This field is required">
            @if ($errors->has('date'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('date') }}</strong>
                </span>
            @endif
        </div>
    </div>
</div>

<div class="col-lg-7 col-md-7 col-xs-12">
    <div class="form-group">
        <h5>Comment<span class="text-danger">*</span></h5>
        <div class="controls">
            <textarea name="comment" class="form-control{{ $errors->has('comment') ? ' is-invalid' : '' }} summernote" required data-validation-required-message="This field is required">{!! old('comment', isset($data) ? $data->comment:'') !!}</textarea>
            @if ($errors->has('comment'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('comment') }}</strong>
                </span>
            @endif
        </div>
    </div>
</div>

resources/views/admin/emp-note/create.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Employee Note Create
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Employee Note Create</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('emp-note.index') !!}">Employee Note</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- End Bread crumb and right sidebar toggle -->


    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-10 col-sm-8">
                                <h4 class="card-title">Employee Note Create</h4>
                            </div>
                            <div class="col-md-2 col-sm-4 text-right">
                                <a href="{!! route('emp-note.index') !!}" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <form class="" method="post" action="{!! route('emp-note.store') !!}" novalidate enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                @include('admin.emp-note._form')
                            </div>

                            <div class="text-xs-right">
                                <button type="submit" class="btn btn-info">Submit</button>
                                <button type="reset" class="btn btn-inverse">Reset</button>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>

        <!-- First Cards Row  -->
    </div>


@endsection

@section('page_js')

@endsection

resources/views/admin/emp-note/edit.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Employee Note | Edit
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">User Edit</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('emp-note.index') !!}">Employee Note</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <!-- End Bread crumb and right sidebar toggle -->

    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-10">
                                <h4 class="card-title">User Update</h4>
                            </div>
                            <div class="col-2 text-right">
                                <a href="{!! route('emp-note.index') !!}" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <form class="" method="post" action="{!! route('emp-note.update', $data->id) !!}" novalidate enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf
                            <div class="row">
                                @include('admin.emp-note._form')
                            </div>
                            <div class="text-xs-right">
                                <button type="submit" class="btn btn-info">Update</button>
                                <button type="reset" class="btn btn-inverse">Reset</button>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>

        <!-- First Cards Row  -->
    </div>


@endsection
@section('page_js')

@endsection

resources/views/admin/emp-note/index.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Employee Notes
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Employee Notes</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Employee Notes</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <!-- End Bread crumb and right sidebar toggle -->


    <!-- Container fluid  -->

    <div class="page-content container-fluid">

    @include('admin.include.alert')
        <!-- First Cards Row  -->
        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-10">
                                <h4 class="card-title">All Employee Notes</h4>
                            </div>
                            <div class="col-md-2 text-right">
                                <a href="{!! route('emp-note.create') !!}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add New</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table id="row_create_call" class="table table-striped table-hover table-bordered display" style="width:100%">
                                <thead>
                                <tr>
                                    <th width="5%">#</th>
                                    <th width="8%">Avatar</th>
                                    <th width="15%">User Info</th>
                                    <th width="8%">Date</th>
                                    <th>Comment</th>
                                    <th width="10%">Action</th>
                                </tr>
                                </thead>
                                <tbody id="tablecontents">
                                    @foreach($data as $key => $note)
                                    <tr>
                                        <td>{!! ++$key !!}</td>
                                        <td class="text-center">
                                            @if($note->user->image)
                                                <img src="{!! asset('media/user/'.$note->user->image) !!}" width="50">
                                            @else
                                                <img src="{!! asset('avatar.png') !!}" width="50">
                                            @endif
                                        </td>
                                        <td>
                                            <h5>{!! $note->user->name !!}</h5>
                                            <h5>{!! $note->user->email !!}</h5>
                                            <h5>
                                                @if($note->user->role == 'management')
                                                    <span class="badge badge-pill badge-success">Management</span>
                                                @else
                                                    <span class="badge badge-pill badge-info">Employee</span>
                                                @endif
                                            </h5>
                                        </td>

                                        <td>{!! date('d M Y', strtotime($note->date)) !!}</td>
                                        <td>{!! substr($note->comment, 0, 100) !!}</td>

                                        <td>
                                            <form action="{{ route('emp-note.destroy', $note->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <a href="{!! route('emp-note.show',$note->id) !!}" class="btn btn-success btn-circle"><i class="fa fa-eye"></i> </a>
                                                <a href="{!! route('emp-note.edit',$note->id) !!}" class="btn btn-info btn-circle"><i class="fa fa-edit"></i> </a>
                                                <button type="submit" onclick="return confirm('Are you sure...?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                            </form>

                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>




@endsection

@section('page_css')
<style>
    td ol, ul{
        margin-left: 20px;
    }
</style>
@endsection

resources/views/admin/emp-note/view.blade.php
@extends('admin.master')

@section('title')
    Mediusware | View
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Emp. Note View</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('emp-note.index') !!}">Emp. Note</a></li>
                        <li class="breadcrumb-item active" aria-current="page">View</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- End Bread crumb and right sidebar toggle -->


    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <!-- Column -->
            <div class="col-lg-4 col-xlg-3 col-md-5">
                <div class="card">
                    <div class="card-body">
                        <center class="mt-4">
                            @if(!empty($data->user))
                                @if($data->user->image)
                                    <img src="{!! asset('media/user/'. $data->user->image) !!}" class="rounded-circle" width="150">
                                @else
                                    <img src="{!! asset('avatar.png') !!}" class="rounded-circle" width="150">
                                @endif
                            @endif


                            <h4 class="card-title mt-2">{!! $data->user->name !!}</h4>
                            <h6 class="card-subtitle">
                                @if($data->user->role == 'employee')
                                    Employee
                                @endif
                            </h6>

                        </center>
                    </div>
                    <div>
                        <hr> </div>
                    <div class="card-body"> <small class="text-muted">Email address </small>
                        <h6>{!! $data->user->email !!}</h6> <small class="text-muted pt-4 db">Phone</small>
                        <h6>{!! $data->user->phone !!}</h6> <small class="text-muted pt-4 db">About</small>
                        <h6 class="text-justify">{!! $data->user->about !!}</h6>
                    </div>
                </div>
            </div>
            <!-- Column -->
            <!-- Column -->
            <div class="col-lg-8 col-xlg-9 col-md-7">
                <div class="card">
                    <div class="card-body">
                        <h3 class="text-info">Date:</h3>
                        <p>{{ date('d M Y', strtotime($data->date)) }}</p>


                        <h3 class="text-info">Comment:</h3>
                        <p>{!! $data->comment !!}</p>
                    </div>
                </div>
            </div>
            <!-- Column -->
        </div>

        <!-- First Cards Row  -->
    </div>


@endsection

@section('page_js')
@endsection