routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WebsiteController@index');

Route::post('/login', 'Auth\LoginController@login');

Auth::routes();

//Admin Route
Route::group(['prefix' => 'taskman', 'middleware' => 'auth'], function(){
    Route::post('users/registerFcmToken', 'Admin\DashboardController@registerFcmToken');

    Route::get('dashboard', 'Admin\DashboardController@index')->name('home');
    Route::get('media/image/{id}/delete', 'Admin\DashboardController@taskImageDelete');


    Route::get('work-list', 'Admin\WorkController@workList');
    Route::get('work/create/{task_id}', 'Admin\WorkController@create');
    Route::resource('work', 'Admin\WorkController');
    Route::post('work/sortable', 'Admin\WorkController@sortable');
    // review
    Route::resource('review', 'Admin\ReviewController');
    Route::post('review/update/{id}', 'Admin\ReviewController@update');

    //Late report
    Route::get('emp-late-report/list', 'Admin\LateReportController@empReportList')->name('emp.list');
    Route::get('emp-monthly-late-report', 'Admin\LateReportController@empMonthlyReportList')->name('emp-late-report.monthly');
    //Leave Application
    Route::resource('leave-application', 'Admin\LeaveApplicationController');

    Route::group(['middleware' => 'management' || 'admin'], function(){
        Route::resource('user', 'Admin\UserController');
        Route::post('update-password/{id}', 'Admin\UserController@updatePassword')->name('user.update-password');
        Route::post('user/sortable', 'Admin\UserController@sortable');
        Route::post('user/reset-password/{id}', 'Admin\UserController@resetPassword');
        Route::post('user/reset-email/{id}', 'Admin\UserController@resetEmail');

        Route::resource('project', 'Admin\ProjectController');
        Route::post('user/project', 'Admin\ProjectController@sortable');

        Route::resource('task', 'Admin\TaskController');
        Route::post('task/sortable', 'Admin\TaskController@sortable');

        //Late report
        Route::get('late-report/list', 'Admin\LateReportController@reportList')->name('late_report.list');
        Route::get('monthly-late-report', 'Admin\LateReportController@monthlyReportList')->name('late-report.monthly');
        Route::get('late-report/filter', 'Admin\LateReportController@filter');
        Route::resource('late-report', 'Admin\LateReportController');

        //Leave
        Route::post('/leave/update', 'Admin\LeaveController@leaveUpdate');
        Route::get('/yearly-leave-report', 'Admin\LeaveController@yearlyLeaveReport');
        Route::resource('leave', 'Admin\LeaveController');

        //Application
        Route::get('casualToSick/{id}', 'Admin\LeaveApplicationController@casualToSick');
        Route::get('sickToCasual/{id}', 'Admin\LeaveApplicationController@sickToCasual');

        Route::get('emp-application', 'Admin\LeaveApplicationController@empApplication')->name('emp.application');
        Route::get('/application/approve/{id}', 'Admin\LeaveApplicationController@applicationApprove');
        Route::get('/application/reject/{id}', 'Admin\LeaveApplicationController@applicationReject');
        Route::resource('application', 'Admin\LeaveApplicationController');
        Route::resource('leave-template', 'Admin\LeaveTemplateController');


        Route::resource('emp-note', 'Admin\EmployeeNoteController');

        //Salary Report
        Route::get('/salary', 'Admin\SalaryController@index');
        Route::get('/year-end-salary', 'Admin\SalaryController@yearEnd');


        //Questionnaire
        Route::resource('/exam', 'Admin\ExamController');
        Route::get('/exam/questions/{exam_id}', 'Admin\ExamController@showQuestions')->name('exam.questions');
        Route::get('/exam/examine/{exam_id}', 'Admin\ExamController@showExamine')->name('exam.show-examine'); // Show Examine List along with Exam ID
        Route::post('/exam/change-activity/{id}', 'Admin\ExamController@changeActivity')->name('exam.change-activity');
        Route::resource('/question', 'Admin\ExamQuestionController');
        Route::post('/question/delete-image/{question}', 'Admin\ExamQuestionController@deleteImage');

        //Admin
        Route::resource('/applicant', 'Admin\ApplicantController');
        Route::get('/applicant/remark_show/{id}', 'Admin\ApplicantController@remark');

        // Exam Answers
        Route::get('/exam/answer/{applicant_id}', 'Admin\ExamAnswerController@showAnswers')->name('exam-answer.show');

    });

});

// This is a test route
Route::get('/interview-email', function (){
    $applicant = \App\Models\Applicant::first();
    return view('admin.exam.email', compact('applicant'));
});
// End of test route

Route::get('/interview-exam/{exam_slug}', 'Admin\ApplicantAnswerController@show')->name('interview-exam.show');
Route::post('/interview-exam/submit/{exam_id}', 'Admin\ApplicantAnswerController@submitAnswer')->name('interview-exam.submit');

resources/views/admin/application/edit.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Application Edit | {!! $application->subject !!}
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Application Edit | {!! $application->subject !!}</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! url('/taskman/application') !!}">applications</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    
    <!-- End Bread crumb and right sidebar toggle -->

    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-10">
                                <h4 class="card-title">Application Update</h4>
                            </div>
                            <div class="col-2 text-right">
                                <a href="{!! route('application.index') !!}" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <form class="" method="post" action="{!! route('application.update', $application->id) !!}" novalidate enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf
                            <div class="row">

                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <h5>Date From<span class="text-danger">*</span></h5>
                                                <div class="input-group">
                                                    <input type="text" class="form-control{{ $errors->has('date_from') ? ' is-invalid' : '' }} datepicker-autoclose" value="{!! old('date_from', $application->date_from) !!}" required data-validation-required-message="This field is required" name="date_from"  placeholder="Date">
                                                    <div class="input-group-append">
                                                        <span class="input-group-text"><i class="icon-calender"></i></span>
                                                    </div>
                                                    @if ($errors->has('date_from'))
                                                        <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('date_from') }}</strong>
                                                </span>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <h5>Date To<span class="text-danger">*</span></h5>
                                                <div class="input-group">
                                                    <input type="text" class="form-control{{ $errors->has('date_to') ? ' is-invalid' : '' }} datepicker-autoclose" value="{!! old('date_to', $application->date_to) !!}" required data-validation-required-message="This field is required" name="date_to"  placeholder="Date">
                                                    <div class="input-group-append">
                                                        <span class="input-group-text"><i class="icon-calender"></i></span>
                                                    </div>
                                                    @if ($errors->has('date_to'))
                                                        <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('date_to') }}</strong>
                                                </span>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Subject<span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <input type="text" name="subject" value="{!! old('subject', $application->subject) !!}" class="form-control{{ $errors->has('subject') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">
                                            @if ($errors->has('subject'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('subject') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Application<span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <textarea name="application" class="form-control{{ $errors->has('application') ? ' is-invalid' : '' }} summernote" required data-validation-required-message="This field is required">{!! old('application', $application->application) !!}</textarea>
                                            @if ($errors->has('application'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('application') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="row">
                                        <div class="col-md-{{ $application->application_file ? '10':'12' }}">
                                            <div class="form-group">
                                                <h5>Application File</h5>
                                                <div class="controls">
                                                    <input type="file" name="application_file" class="form-control{{ $errors->has('application_file') ? ' is-invalid' : '' }}" accept="image/*, application/pdf">
                                                    @if ($errors->has('application_file'))
                                                        <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('application_file') }}</strong>
                                                </span>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                        @if($application->application_file)
                                        <div class="col-md-2">
                                            <br>
                                            @if($fileExt == 'pdf')
                                                <a target="_blank" href="{{ asset('media/application-file/'. $application->application_file) }}" class="btn btn-info pull-right"><i class="fa fa-file"></i> View File</a>
                                            @else
                                                <a href="{{ asset('media/application-file/'. $application->application_file) }}" class="btn btn-info pull-right image-popup-vertical-fit"><i class="fa fa-file"></i> View File</a>
                                            @endif
                                        </div>
                                        @endif
                                    </div>
                                </div>



                                <div class="col-md-7">
                                    <div class="form-group validate">
                                        <h5>Leave Type <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <fieldset>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" name="leave_type" {!! $application->leave_type == 'casual_leave' ? 'checked':'' !!} value="casual_leave" required="" id="casual_leave" class="custom-control-input" aria-invalid="false">
                                                    <label class="custom-control-label" for="casual_leave">Casual Leave</label>
                                                </div>
                                            </fieldset>
                                            <fieldset>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio"  name="leave_type" {!! $application->leave_type == 'sick_leave' ? 'checked':'' !!} value="sick_leave" id="sick_leave" class="custom-control-input" aria-invalid="false">
                                                    <label class="custom-control-label" for="sick_leave">Sick Leave</label>
                                                </div>
                                            </fieldset>
                                            @if ($errors->has('leave_type'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('leave_type') }}</strong>
                                                </span>
                                            @endif
                                            <div class="help-block"></div>
                                        </div>
                                    </div>
                                    <hr>
                                </div>
                            </div>


                            <div class="text-xs-right">
                                <button type="submit" class="btn btn-info">Update</button>
                                <button type="reset" class="btn btn-inverse">Reset</button>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>
        
        <!-- First Cards Row  -->
    </div>


@endsection
@section('page_js')

@endsection

resources/views/admin/application/index.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Applications
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Applications</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Applications</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    
    <!-- End Bread crumb and right sidebar toggle -->
    
    
    <!-- Container fluid  -->

    <div class="page-content container-fluid">

    @include('admin.include.alert')
        <!-- First Cards Row  -->
        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-10">
                                <h4 class="card-title">All Applications</h4>
                            </div>
                            <div class="col-md-2 text-right">
                                <a href="{!! route('application.create') !!}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add New</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table id="row_create_call" class="table table-striped table-hover table-bordered display" style="width:100%">
                                <thead>
                                <tr>
                                    <th width="5%">#</th>
                                    <th>Subject</th>
                                    <th>Leave Type</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th width="10%">Action</th>
                                </tr>
                                </thead>
                                <tbody id="tablecontents">
                                    @foreach($applications as $key => $application)
                                    <tr class="row1" data-id="{{ $application->id }}">
                                        <td>{!! ++$key !!}</td>

                                        <td>{!! $application->subject !!}</td>
                                        <td>
                                            @if($application->leave_type == 'casual_leave')
                                                Casual Leave
                                            @else
                                                Sick Leave
                                            @endif
                                        </td>
                                        <td class="text-center">
                                            {!! date('F d, Y', strtotime($application->date_from)).' - '. date('F d, Y', strtotime($application->date_to)) !!}<br>
                                            ({!! $application->date_count !!} Day)
                                        </td>

                                        <td>
                                            @if($application->status == 'pending')
                                                <span style="font-size: 18px;" class="badge badge-pill badge-warning">Pending</span>
                                            @elseif($application->status == 'approved')
                                                <span style="font-size: 18px;" class="badge badge-pill badge-success">Approved</span>
                                            @else
                                                <span style="font-size: 18px;" class="badge badge-pill badge-danger">Rejected</span>
                                            @endif
                                        </td>
                                        <td>
                                            <form action="{{ route('application.destroy', $application->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <a href="javascript:void(0)" data-id="{{ $application->id }}" data-toggle="modal" data-target="#portfolioModal" class="btn btn-success btn-circle viewPortfolio"><i class="fa fa-eye"></i> </a>
                                                @if($application->status == 'pending')
                                                    <a href="{!! url('taskman/application/'.$application->id) !!}/edit" class="btn btn-info btn-circle"><i class="fa fa-edit"></i> </a>
                                                    <button type="submit" onclick="return confirm('Are you sure...?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                                @endif
                                            </form>

                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="modal fade bs-example-modal-lg" id="portfolioModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none; z-index: 1041;">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myLargeModalLabel">Application</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <div class="modal-body">
                        <p><b id="date"></b></p>
                        <p style="margin-top: -15px;">Subject: <b id="subject"></b></p>
                        <p id="body"></p>
                        <p class="text-capitalize">Leave Type: <b id="leaveType"></b></p>
                        <p style="margin-top: -15px;" class="text-capitalize">Status: <b id="status"></b></p>

                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered text-center">
                            <tr>
                                <th>#</th>
                                <th>Casual Leave</th>
                                <th>Sick Leave</th>
                            </tr>

                            <tr>
                                <th>Leaves</th>
                                <td id="casualLeave">Casual Leave</td>
                                <td id="sickLeave">Sick Leave</td>
                            </tr>

                            <tr>
                                <th>Get Leave</th>
                                <td id="tCasual">Casual Leave</td>
                                <td id="tSick">Sick Leave</td>
                            </tr>

                            <tr>
                                <th>Remaining Leave</th>
                                <td id="reCasual">Casual Leave</td>
                                <td id="reSick">Sick Leave</td>
                            </tr>

                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <a id="appFilePdf" target="_blank" style="display: none" class="btn btn-rounded btn-outline-success mr-2 btn-sm"><i class="fa fa-file"></i> Show File</a>
                    <a id="appFileImg" style="display: none" class="btn btn-rounded btn-outline-success mr-2 btn-sm image-popup-vertical-fit"><i class="fa fa-file"></i> Show File</a>
                    <button type="button" class="btn btn-danger waves-effect text-left" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

@endsection

@section('page_js')
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(".viewPortfolio").click(function (e) {
            var id = $(this).attr("data-id");
            e.preventDefault();
            $.ajax({
                type: "get",
                url: "{!! url('taskman/application/') !!}/" + id,
                success: function (data) {
                    $("#date").html(data.date);
                    $("#subject").html(data.obj.subject);
                    $("#body").html(data.obj.application);
                    $("#leaveType").html(data.leave_type);
                    $("#status").html(data.obj.status);
                    $("#tCasual").html(data.obj.t_casual);
                    $("#tSick").html(data.obj.t_sick);
                    $("#casualLeave").html(data.leave.casual_leave);
                    $("#sickLeave").html(data.leave.sick_leave);
                    $("#reCasual").html(data.leave.casual_leave - data.obj.t_casual);
                    $("#reSick").html(data.leave.sick_leave - data.obj.t_sick);

                    if (data.check_file == ''){
                        $("#appFilePdf").hide();
                        $("#appFileImg").hide()
                    } else {
                        if (data.check_file == 'pdf') {
                            $("#appFileImg").hide();
                            $("#appFilePdf").show();
                            $("a#appFilePdf").attr("href", data.file_path);
                        }else {
                            $("#appFilePdf").hide();
                            $("#appFileImg").show();
                            $("a#appFileImg").attr("href", data.file_path);
                        }
                    }

                }
            });
        });

    </script>
@endsection