routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WebsiteController@index');

Route::post('/login', 'Auth\LoginController@login');

Auth::routes();

//Admin Route
Route::group(['prefix' => 'taskman', 'middleware' => 'auth'], function(){
    Route::post('users/registerFcmToken', 'Admin\DashboardController@registerFcmToken');

    Route::get('dashboard', 'Admin\DashboardController@index')->name('home');
    Route::get('media/image/{id}/delete', 'Admin\DashboardController@taskImageDelete');


    Route::get('work-list', 'Admin\WorkController@workList');
    Route::get('work/create/{task_id}', 'Admin\WorkController@create');
    Route::resource('work', 'Admin\WorkController');
    Route::post('work/sortable', 'Admin\WorkController@sortable');
    // review
    Route::resource('review', 'Admin\ReviewController');
    Route::post('review/update/{id}', 'Admin\ReviewController@update');

    //Late report
    Route::get('emp-late-report/list', 'Admin\LateReportController@empReportList')->name('emp.list');
    Route::get('emp-monthly-late-report', 'Admin\LateReportController@empMonthlyReportList')->name('emp-late-report.monthly');
    //Leave Application
    Route::resource('leave-application', 'Admin\LeaveApplicationController');

    Route::group(['middleware' => 'management' || 'admin'], function(){
        Route::resource('user', 'Admin\UserController');
        Route::post('update-password/{id}', 'Admin\UserController@updatePassword')->name('user.update-password');
        Route::post('user/sortable', 'Admin\UserController@sortable');
        Route::post('user/reset-password/{id}', 'Admin\UserController@resetPassword');
        Route::post('user/reset-email/{id}', 'Admin\UserController@resetEmail');

        Route::resource('project', 'Admin\ProjectController');
        Route::post('user/project', 'Admin\ProjectController@sortable');

        Route::resource('task', 'Admin\TaskController');
        Route::post('task/sortable', 'Admin\TaskController@sortable');

        //Late report
        Route::get('late-report/list', 'Admin\LateReportController@reportList')->name('late_report.list');
        Route::get('monthly-late-report', 'Admin\LateReportController@monthlyReportList')->name('late-report.monthly');
        Route::get('late-report/filter', 'Admin\LateReportController@filter');
        Route::resource('late-report', 'Admin\LateReportController');

        //Leave
        Route::post('/leave/update', 'Admin\LeaveController@leaveUpdate');
        Route::get('/yearly-leave-report', 'Admin\LeaveController@yearlyLeaveReport');
        Route::resource('leave', 'Admin\LeaveController');

        //Application
        Route::get('casualToSick/{id}', 'Admin\LeaveApplicationController@casualToSick');
        Route::get('sickToCasual/{id}', 'Admin\LeaveApplicationController@sickToCasual');

        Route::get('emp-application', 'Admin\LeaveApplicationController@empApplication')->name('emp.application');
        Route::get('/application/approve/{id}', 'Admin\LeaveApplicationController@applicationApprove');
        Route::get('/application/reject/{id}', 'Admin\LeaveApplicationController@applicationReject');
        Route::resource('application', 'Admin\LeaveApplicationController');
        Route::resource('leave-template', 'Admin\LeaveTemplateController');


        Route::resource('emp-note', 'Admin\EmployeeNoteController');

        //Salary Report
        Route::get('/salary', 'Admin\SalaryController@index');
        Route::get('/year-end-salary', 'Admin\SalaryController@yearEnd');


        //Questionnaire
        Route::resource('/exam', 'Admin\ExamController');
        Route::get('/exam/questions/{exam_id}', 'Admin\ExamController@showQuestions')->name('exam.questions');
        Route::get('/exam/examine/{exam_id}', 'Admin\ExamController@showExamine')->name('exam.show-examine'); // Show Examine List along with Exam ID
        Route::post('/exam/change-activity/{id}', 'Admin\ExamController@changeActivity')->name('exam.change-activity');
        Route::resource('/question', 'Admin\ExamQuestionController');
        Route::post('/question/delete-image/{question}', 'Admin\ExamQuestionController@deleteImage');

        //Admin
        Route::resource('/applicant', 'Admin\ApplicantController');
        Route::get('/applicant/remark_show/{id}', 'Admin\ApplicantController@remark');

        // Exam Answers
        Route::get('/exam/answer/{applicant_id}', 'Admin\ExamAnswerController@showAnswers')->name('exam-answer.show');

    });

});

// This is a test route
Route::get('/interview-email', function (){
    $applicant = \App\Models\Applicant::first();
    return view('admin.exam.email', compact('applicant'));
});
// End of test route

Route::get('/interview-exam/{exam_slug}', 'Admin\ApplicantAnswerController@show')->name('interview-exam.show');
Route::post('/interview-exam/submit/{exam_id}', 'Admin\ApplicantAnswerController@submitAnswer')->name('interview-exam.submit');

resources/views/admin/include/alert.blade.php
@if (session('success'))
    <div class="alert alert-success"> <i class="fa fa-check-circle"></i>
        <b> {{ session('success') }}</b>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    </div>
@elseif(session('error'))
    <div class="alert alert-danger"> <i class="fa fa-exclamation-triangle"></i>
        <b> {{ session('error') }}</b>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    </div>
@endif

resources/views/admin/include/footer.blade.php
<footer class="footer text-center">
    Copyright {!! date('Y') !!} © All Rights Reserved
    <a href="https://mediusware.com">Mediusware</a>
</footer>

resources/views/admin/include/header.blade.php
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header border-right">
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            <a class="navbar-brand" href="{{ url('taskman/dashboard') }}">
                <b class="logo-icon">
                    <img src="{!! asset('admin') !!}/images/logos/logo-icon.png" alt="homepage" class="dark-logo" style="width: 100%" />
                    <!-- Light Logo icon -->
                    <img src="{!! asset('admin') !!}/images/logos/logo-light-icon.png" alt="homepage" class="light-logo" style="width: 100%" />
                </b>
                <span class="logo-text">
                    <img src="{!! asset('admin') !!}/images/logos/logo-text.png" alt="homepage" class="dark-logo" />
                    <img src="{!! asset('admin') !!}/images/logos/logo-light-text.png" class="light-logo" alt="homepage" />
                </span>
            </a>
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="navbar-nav float-left mr-auto">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-18"></i></a></li>

{{--                <li class="nav-item dropdown">--}}
{{--                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="#" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="font-18 mdi mdi-gmail"></i>--}}
{{--                        <div class="notify">--}}
{{--                            <span class="heartbit"></span>--}}
{{--                            <span class="point"></span>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <div class="dropdown-menu dropdown-menu-left mailbox animated bounceInDown" aria-labelledby="2">--}}
{{--                        <ul class="list-style-none">--}}
{{--                            <li>--}}
{{--                                <div class="drop-title border-bottom">You have 4 new messanges</div>--}}
{{--                            </li>--}}
{{--                            <li>--}}
{{--                                <div class="message-center message-body">--}}
{{--                                    <!-- Message -->--}}
{{--                                    <a href="javascript:void(0)" class="message-item">--}}
{{--                                        <span class="user-img">--}}
{{--                                            <img src="{!! asset('admin') !!}/images/users/1.jpg" alt="user" class="rounded-circle">--}}
{{--                                            <span class="profile-status online pull-right"></span>--}}
{{--                                        </span>--}}
{{--                                        <span class="mail-contnet">--}}
{{--                                                    <h5 class="message-title">Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span> </span>--}}
{{--                                    </a>--}}
{{--                                    <!-- Message -->--}}
{{--                                    <a href="javascript:void(0)" class="message-item">--}}
{{--                                        <span class="user-img"> <img src="{!! asset('admin') !!}/images/users/2.jpg" alt="user" class="rounded-circle"> <span class="profile-status busy pull-right"></span> </span>--}}
{{--                                        <span class="mail-contnet">--}}
{{--                                                    <h5 class="message-title">Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </span>--}}
{{--                                    </a>--}}
{{--                                    <!-- Message -->--}}
{{--                                    <a href="javascript:void(0)" class="message-item">--}}
{{--                                        <span class="user-img"> <img src="{!! asset('admin') !!}/images/users/3.jpg" alt="user" class="rounded-circle"> <span class="profile-status away pull-right"></span> </span>--}}
{{--                                        <span class="mail-contnet">--}}
{{--                                                    <h5 class="message-title">Arijit Sinh</h5> <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span> </span>--}}
{{--                                    </a>--}}
{{--                                    <!-- Message -->--}}
{{--                                    <a href="javascript:void(0)" class="message-item">--}}
{{--                                        <span class="user-img"> <img src="{!! asset('admin') !!}/images/users/4.jpg" alt="user" class="rounded-circle"> <span class="profile-status offline pull-right"></span> </span>--}}
{{--                                        <span class="mail-contnet">--}}
{{--                                                    <h5 class="message-title">Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </span>--}}
{{--                                    </a>--}}
{{--                                </div>--}}
{{--                            </li>--}}
{{--                            <li>--}}
{{--                                <a class="nav-link text-center link text-dark" href="javascript:void(0);"> <b>See all Notifications</b> <i class="fa fa-angle-right"></i> </a>--}}
{{--                            </li>--}}
{{--                        </ul>--}}
{{--                    </div>--}}
{{--                </li>--}}

            </ul>

            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
{{--                <li class="nav-item search-box">--}}
{{--                    <form class="app-search d-none d-lg-block">--}}
{{--                        <input type="text" class="form-control" placeholder="Search...">--}}
{{--                        <a href="#" class="active"><i class="fa fa-search"></i></a>--}}
{{--                    </form>--}}
{{--                </li>--}}
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @if(Auth::check())
                            @if(Auth::user()->image)
                                <img src="{!! asset('media/user/'. Auth::user()->image) !!}" alt="user" class="rounded-circle" width="36">
                            @else
                                <img src="{!! asset('avatar.png') !!}" alt="user" class="rounded-circle" width="36">
                            @endif
                        @endif

                        <span class="ml-2 font-medium">{!! Auth::user()->name !!}</span><span class="fas fa-angle-down ml-2"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                        <div class="d-flex no-block align-items-center p-3 mb-2 border-bottom">
                            <div class="">
                                @if(Auth::check())
                                    @if(Auth::user()->image)
                                        <img src="{!! asset('media/user/'. Auth::user()->image) !!}" alt="user" class="rounded" width="80">
                                    @else
                                        <img src="{!! asset('avatar.png') !!}" alt="user" class="rounded" width="80">
                                    @endif
                                @endif
                            </div>
                            <div class="ml-2">
                                <h4 class="mb-0">{!! Auth::user()->name !!}</h4>
                                <p class=" mb-0 text-muted">{!! Auth::user()->email !!}</p>
                                <a href="{!! route('user.show', Auth::user()->id) !!}" class="btn btn-sm btn-danger text-white mt-2 btn-rounded">View Profile</a>
                            </div>
                        </div>

                        <a class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" href="javascript:void(0)">
                            <i class="fa fa-power-off mr-1 ml-1"></i> Logout
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/include/navbar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark profile-dd" href="javascript:void(0)" aria-expanded="false">
                        @if(Auth::check())
                            @if(Auth::user()->image)
                            <img src="{!! asset('media/user/'. Auth::user()->image) !!}" class="rounded-circle ml-2" width="30">
                            @else
                            <img src="{!! asset('avatar.png') !!}" class="rounded-circle ml-2" width="30">
                            @endif
                            <span class="hide-menu">{!! Auth::user()->name !!} </span>
                        @endif
                    </a>
                    <ul aria-expanded="false" class="collapse  first-level">
                        <li class="sidebar-item">
                            <a href="{!! route('user.show', Auth::user()->id) !!}" class="sidebar-link">
                                <i class="ti-user"></i>
                                <span class="hide-menu"> My Profile </span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a href="javascript:void(0)" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" href="javascript:void(0)" class="sidebar-link">
                                <i class="fas fa-power-off"></i>
                                <span class="hide-menu"> Logout </span>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>

                <li class="sidebar-item">
                    <a href="{!! route('home') !!}" class="sidebar-link">
                        <i class="mdi mdi-view-dashboard"></i>
                        <span class="hide-menu"> Dashboard </span>
                    </a>
                </li>
                <div class="devider"></div>

                <li class="sidebar-item {!! Request::is('taskman/work*') ? 'selected':'' !!}">
                    <a href="{!! route('work.index') !!}" class="sidebar-link {!! Request::is('taskman/work*') ? 'active':'' !!}">
                        <i class="fa fa-briefcase"></i>
                        <span class="hide-menu">My Works </span>
                    </a>
                </li>
                <div class="devider"></div>

                <li class="sidebar-item {!! Request::is('taskman/application*') ? 'selected':'' !!}">
                    <a href="{!! route('application.index') !!}" class="sidebar-link {!! Request::is('taskman/application*') ? 'active':'' !!}">
                        <i class="far fa-sticky-note"></i>
                        <span class="hide-menu">My Leave Application</span>
                    </a>
                </li>
                <div class="devider"></div>

                @if(Auth::user()->role == 'employee')
                <li class="sidebar-item {!! Request::is('taskman/late-report*') || Request::is('taskman/emp-monthly-late-report*') ? 'selected':'' !!}">
                    <a href="{!! route('emp.list') !!}" class="sidebar-link {!! Request::is('taskman/late-report*') || Request::is('taskman/emp-monthly-late-report*') ? 'active':'' !!}">
                        <i class="fa fa-info"></i>
                        <span class="hide-menu">My Late Report </span>
                    </a>
                </li>
                <div class="devider"></div>
                @endif

                @if(Auth::user()->role == 'admin' || Auth::user()->role == 'management')
                    <li class="sidebar-item {!! Request::is('taskman/task*') ? 'selected':'' !!}">
                        <a href="{!! route('task.index') !!}" class="sidebar-link {!! Request::is('taskman/task*') ? 'active':'' !!}">
                            <i class="fa fa-tasks"></i>
                            <span class="hide-menu"> Assign Tasks </span>
                        </a>
                    </li>
                    <div class="devider"></div>

                    <li class="sidebar-item {!! Request::is('taskman/late-report*') ? 'selected':'' !!}">
                        <a href="{!! route('late-report.index') !!}" class="sidebar-link {!! Request::is('taskman/late-report*') ? 'active':'' !!}">
                            <i class="fa fa-info"></i>
                            <span class="hide-menu">Emp. Late Report List </span>
                        </a>
                    </li>
                    <div class="devider"></div>

                    <li class="sidebar-item {!! Request::is('taskman/emp-application*') ? 'selected':'' !!}">
                        <a href="{!! route('emp.application') !!}" class="sidebar-link {!! Request::is('taskman/emp-application*') ? 'active':'' !!}">
                            <i class="far fa-sticky-note"></i>
                            <span class="hide-menu">Emp. Leave Application</span>
                        </a>
                    </li>
                    <div class="devider"></div>

                    <li class="sidebar-item {!! Request::is('taskman/exam*') ? 'selected':'' !!}">
                        <a href="{!! route('exam.index') !!}" class="sidebar-link {!! Request::is('taskman/exam*') ? 'active':'' !!}">
                            <i class="fas fa-question"></i>
                            <span class="hide-menu">Interview Exam</span>
                        </a>
                    </li>
                    <div class="devider"></div>

                    <li class="sidebar-item {!! Request::is('taskman/emp-note*') ? 'selected':'' !!}">
                        <a href="{!! route('emp-note.index') !!}" class="sidebar-link {!! Request::is('taskman/emp-note*') ? 'active':'' !!}">
                            <i class="fa fa-pencil-alt"></i>
                            <span class="hide-menu">Emp. Notes</span>
                        </a>
                    </li>
                    <div class="devider"></div>

                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                            <i class="fa fa-info-circle"></i>
                            <span class="hide-menu">Reports</span>
                        </a>
                        <ul aria-expanded="false" class="collapse first-level">

                            <li class="sidebar-item {!! Request::is('taskman/monthly-late-report*') ? 'active':'' !!}">
                                <a href="{!! route('late-report.monthly') !!}" class="sidebar-link {!! Request::is('taskman/monthly-late-report*') ? 'active':'' !!}">
                                    <i class="mdi mdi-cards-variant"></i>
                                    <span class="hide-menu">Monthly Late Report </span>
                                </a>
                            </li>

                            <li class="sidebar-item {!! Request::is('taskman/yearly-leave-report*') ? 'active':'' !!}">
                                <a href="{!! url('taskman/yearly-leave-report') !!}" class="sidebar-link {!! Request::is('taskman/yearly-leave-report*') ? 'active':'' !!}">
                                    <i class="mdi mdi-cards-variant"></i>
                                    <span class="hide-menu">Yearly Leave Report </span>
                                </a>
                            </li>

                            <li class="sidebar-item {!! Request::is('taskman/salary*') ? 'active':'' !!}">
                                <a href="{!! url('taskman/salary') !!}" class="sidebar-link {!! Request::is('taskman/salary*') ? 'active':'' !!}">
                                    <i class="mdi mdi-cards-variant"></i>
                                    <span class="hide-menu">Salary Report </span>
                                </a>
                            </li>

                            <li class="sidebar-item {!! Request::is('taskman/year-end-salary*') ? 'active':'' !!}">
                                <a href="{!! url('taskman/year-end-salary') !!}" class="sidebar-link {!! Request::is('taskman/year-end-salary*') ? 'active':'' !!}">
                                    <i class="mdi mdi-cards-variant"></i>
                                    <span class="hide-menu">Year End Salary Report </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <div class="devider"></div>

                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                            <i class="fa fa-cogs"></i>
                            <span class="hide-menu">Settings</span>
                        </a>
                        <ul aria-expanded="false" class="collapse first-level">

                            <li class="sidebar-item {!! Request::is('taskman/project*') ? 'active':'' !!}">
                                <a href="{!! route('project.index') !!}" class="sidebar-link {!! Request::is('taskman/project*') ? 'active':'' !!}">
                                    <i class="mdi mdi-cards-variant"></i>
                                    <span class="hide-menu"> Project </span>
                                </a>
                            </li>

                            <li class="sidebar-item {!! Request::is('taskman/user*') ? 'active':'' !!}">
                                <a href="{!! route('user.index') !!}" class="sidebar-link {!! Request::is('taskman/user*') ? 'active':'' !!}">
                                    <i class="mdi mdi-cards-variant"></i>
                                    <span class="hide-menu"> Employee </span>
                                </a>
                            </li>


                            <li class="sidebar-item {!! Request::is('taskman/leave*') ? 'selected':'' !!}">
                                <a href="{!! route('leave.index') !!}" class="sidebar-link {!! Request::is('taskman/leave*') ? 'active':'' !!}">
                                    <i class="fas fa-clipboard"></i>
                                    <span class="hide-menu">Emp. Leave </span>
                                </a>
                            </li>

                            <li class="sidebar-item {!! Request::is('taskman/leave-template*') ? 'active':'' !!}">
                                <a href="{!! route('leave-template.index') !!}" class="sidebar-link {!! Request::is('taskman/leave-template*') ? 'active':'' !!}">
                                    <i class="mdi mdi-cards-variant"></i>
                                    <span class="hide-menu">Leave Template</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <div class="devider"></div>



                @endif


            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>