routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WebsiteController@index');

Route::post('/login', 'Auth\LoginController@login');

Auth::routes();

//Admin Route
Route::group(['prefix' => 'taskman', 'middleware' => 'auth'], function(){
    Route::post('users/registerFcmToken', 'Admin\DashboardController@registerFcmToken');

    Route::get('dashboard', 'Admin\DashboardController@index')->name('home');
    Route::get('media/image/{id}/delete', 'Admin\DashboardController@taskImageDelete');


    Route::get('work-list', 'Admin\WorkController@workList');
    Route::get('work/create/{task_id}', 'Admin\WorkController@create');
    Route::resource('work', 'Admin\WorkController');
    Route::post('work/sortable', 'Admin\WorkController@sortable');
    // review
    Route::resource('review', 'Admin\ReviewController');
    Route::post('review/update/{id}', 'Admin\ReviewController@update');

    //Late report
    Route::get('emp-late-report/list', 'Admin\LateReportController@empReportList')->name('emp.list');
    Route::get('emp-monthly-late-report', 'Admin\LateReportController@empMonthlyReportList')->name('emp-late-report.monthly');
    //Leave Application
    Route::resource('leave-application', 'Admin\LeaveApplicationController');

    Route::group(['middleware' => 'management' || 'admin'], function(){
        Route::resource('user', 'Admin\UserController');
        Route::post('update-password/{id}', 'Admin\UserController@updatePassword')->name('user.update-password');
        Route::post('user/sortable', 'Admin\UserController@sortable');
        Route::post('user/reset-password/{id}', 'Admin\UserController@resetPassword');
        Route::post('user/reset-email/{id}', 'Admin\UserController@resetEmail');

        Route::resource('project', 'Admin\ProjectController');
        Route::post('user/project', 'Admin\ProjectController@sortable');

        Route::resource('task', 'Admin\TaskController');
        Route::post('task/sortable', 'Admin\TaskController@sortable');

        //Late report
        Route::get('late-report/list', 'Admin\LateReportController@reportList')->name('late_report.list');
        Route::get('monthly-late-report', 'Admin\LateReportController@monthlyReportList')->name('late-report.monthly');
        Route::get('late-report/filter', 'Admin\LateReportController@filter');
        Route::resource('late-report', 'Admin\LateReportController');

        //Leave
        Route::post('/leave/update', 'Admin\LeaveController@leaveUpdate');
        Route::get('/yearly-leave-report', 'Admin\LeaveController@yearlyLeaveReport');
        Route::resource('leave', 'Admin\LeaveController');

        //Application
        Route::get('casualToSick/{id}', 'Admin\LeaveApplicationController@casualToSick');
        Route::get('sickToCasual/{id}', 'Admin\LeaveApplicationController@sickToCasual');

        Route::get('emp-application', 'Admin\LeaveApplicationController@empApplication')->name('emp.application');
        Route::get('/application/approve/{id}', 'Admin\LeaveApplicationController@applicationApprove');
        Route::get('/application/reject/{id}', 'Admin\LeaveApplicationController@applicationReject');
        Route::resource('application', 'Admin\LeaveApplicationController');
        Route::resource('leave-template', 'Admin\LeaveTemplateController');


        Route::resource('emp-note', 'Admin\EmployeeNoteController');

        //Salary Report
        Route::get('/salary', 'Admin\SalaryController@index');
        Route::get('/year-end-salary', 'Admin\SalaryController@yearEnd');


        //Questionnaire
        Route::resource('/exam', 'Admin\ExamController');
        Route::get('/exam/questions/{exam_id}', 'Admin\ExamController@showQuestions')->name('exam.questions');
        Route::get('/exam/examine/{exam_id}', 'Admin\ExamController@showExamine')->name('exam.show-examine'); // Show Examine List along with Exam ID
        Route::post('/exam/change-activity/{id}', 'Admin\ExamController@changeActivity')->name('exam.change-activity');
        Route::resource('/question', 'Admin\ExamQuestionController');
        Route::post('/question/delete-image/{question}', 'Admin\ExamQuestionController@deleteImage');

        //Admin
        Route::resource('/applicant', 'Admin\ApplicantController');
        Route::get('/applicant/remark_show/{id}', 'Admin\ApplicantController@remark');

        // Exam Answers
        Route::get('/exam/answer/{applicant_id}', 'Admin\ExamAnswerController@showAnswers')->name('exam-answer.show');

    });

});

// This is a test route
Route::get('/interview-email', function (){
    $applicant = \App\Models\Applicant::first();
    return view('admin.exam.email', compact('applicant'));
});
// End of test route

Route::get('/interview-exam/{exam_slug}', 'Admin\ApplicantAnswerController@show')->name('interview-exam.show');
Route::post('/interview-exam/submit/{exam_id}', 'Admin\ApplicantAnswerController@submitAnswer')->name('interview-exam.submit');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Auth;

class Task extends Model
{
    protected $table = 'tasks';

    public function employees(){
        return $this->hasMany('App\Models\TaskEmployeeRelation', 'task_id', 'id');
    }

    public function supervisor(){
        return $this->belongsTo('App\User', 'super_vision', 'id');
    }

    public function images(){
        return $this->hasMany('App\Models\MediaImage', 'task_id', 'id');
    }

    public function taskLists(){
        return $this->hasMany('App\Models\TaskList', 'task_id', 'id');
    }

    public function project(){
        return $this->belongsTo('App\Models\Project', 'project_id', 'id');
    }

    public function works(){
        return $this->hasMany('App\Models\Work', 'task_id', 'id');
    }

    public function checkWorks(){
        return $this->hasMany('App\Models\Work', 'task_id', 'id')->where('employee_id', Auth::user()->id);
    }
}

app/Http/Controllers/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\MediaImage;
use App\Models\Project;
use App\Models\Review;
use App\Models\Task;
use App\Models\TaskEmployeeRelation;
use App\Models\TaskList;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use Illuminate\Validation\Rule;
use Validator;
use Auth;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::orderBy('sort', 'ASC')->get();
        return view('admin.tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employees = User::where('role', 'employee')->orderBy('sort', 'ASC')->get();
        $projects = Project::get();
        return view('admin.tasks.create', compact('employees', 'projects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'employee' => 'required',
            'name' => 'required|max:191',
            'task_details' => 'required',
            'start_date' => 'required|date',
            'end_date' => 'required|date',
            'status' => Rule::in(['active', 'deactivate', 'complete']),
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        $startTimeStamp = strtotime($request->start_date);
        $endTimeStamp = strtotime($request->end_date);
        $timeDiff = abs($endTimeStamp - $startTimeStamp);
        $numberDays = $timeDiff/86400;  // 86400 seconds in one day
        $numberDays = 1 + intval($numberDays);

        $task = new Task();
        $task->super_vision = Auth::user()->id;
        $task->project_id   = $request->project;
        $task->name         = $request->name;
        $task->task_details = $request->task_details;
        $task->start_date   = $request->start_date;
        $task->end_date     = $request->end_date;
        $task->ratio        = $numberDays;
        $task->note         = $request->note;
        $task->status       = $request->status;
        if ($task->save()){
            if (!empty($data['employee'])) {
                $employeeData = [];
                foreach ($data['employee'] as $k => $employeeId) {
                    $employeeData[] = [
                        'task_id' => $task->id,
                        'employee_id' => $employeeId,
                    ];
                }
                if (!empty($employeeData)) {
                    TaskEmployeeRelation::insert($employeeData);
                }
            }

            if (!empty($data['task_list'])) {
                //array filter for zero empty value check
                $task_lists = $data['task_list'];
                $task_lists = !empty($task_lists) ? array_values(array_filter($task_lists)) : array();
                $listData = [];
                foreach ($task_lists as $k => $task_list) {
                    $listData[] = [
                        'task_id'   => $task->id,
                        'list_name' => $task_list,
                    ];
                }
                if (!empty($listData)) {
                    TaskList::insert($listData);
                }
            }

            if($request->hasfile('images'))
            {
                $images = [];
                foreach($request->file('images') as $key => $image)
                {
                    $name = $image->getClientOriginalName();
                    $mainName = time().'_'. $name;
                    $image->move(public_path().'/media/task/',$mainName);
                    $images[] = [
                        'task_id' => $task->id,
                        'image' => $mainName,
                    ];
                }

                if (!empty($images)) {
                    MediaImage::insert($images);
                }
            }

            // Send Push Notification
            if (!empty($data['employee'])) {
                foreach ($data['employee'] as $k => $employeeId) {
                    foreach (getUserFcmToken($employeeId) as $fcmToken):
                        $post = array(
                            "to" => $fcmToken->fcm_token,
                            "collapse_key" => "green",
                            "notification" => [
                                "title" => "Your have a task",
                                "body" => "$request->name",
                                "icon" => asset('/admin/images/logos/logo-icon.png'),
                                "image" => "",
                            ]
                        );
                        fcmFire($post);
                    endforeach;
                }
            }

        }


        if (!empty($data['employee'])) {
            $employeeDatas = [];
            foreach ($data['employee'] as $k => $employeeId) {
                $employeeDatas[] = User::findOrFail($employeeId);
            }
        }

        foreach ($employeeDatas as $employeeData){
            $email = $employeeData->email;
            Mail::send('emails.task', [
                'supervisor_name' => Auth::user()->name,
                'employee_name'   => $employeeData->name,
                'project_name'    => $task->project->project_name,
                'task_name'       => $request->name,
                'start_date'      => $request->start_date,
                'end_date'        => $request->end_date,
                'ratio'           => $numberDays,
            ], function ($msg) use ($email, $request)
                {
                    $msg->from('info@mediusware.com', 'MediusWare.Com');
                    $msg->subject('You have a new Task');
                    $msg->to($email);
                });
        }

        return redirect(route('task.index'))->with('success', 'Task Save Successfully');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::find($id);
        $reviews = Review::where('task_id', $id)->orderBy('date', 'DESC')->get();
        $upReview = Review::where('task_id', $id)->where('date', date('Y-m-d'))->first();
        return view('admin.tasks.view', compact('task', 'reviews', 'upReview'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);
        $task->employees = $task->employees->pluck('employee_id')->toArray();
        $employees = User::where('role', 'employee')->orderBy('sort', 'ASC')->get();
        $projects = Project::get();
//        return $task;
        return view('admin.tasks.edit', compact('task', 'employees', 'projects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'employee' => 'required',
            'name' => 'required|max:191',
            'task_details' => 'required',
            'start_date' => 'required|date',
            'end_date' => 'required|date',
            'status' => Rule::in(['active', 'deactivate', 'complete']),
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        $startTimeStamp = strtotime($request->start_date);
        $endTimeStamp = strtotime($request->end_date);
        $timeDiff = abs($endTimeStamp - $startTimeStamp);
        $numberDays = $timeDiff/86400;  // 86400 seconds in one day
        $numberDays = 1 + intval($numberDays);

        $task = Task::find($id);
        $task->name         = $request->name;
        $task->project_id   = $request->project;
        $task->task_details = $request->task_details;
        $task->start_date   = $request->start_date;
        $task->end_date     = $request->end_date;
        $task->ratio        = $numberDays;
        $task->note         = $request->note;
        $task->status       = $request->status;
        if ($task->save()){
            if (!empty($data['employee'])) {
                TaskEmployeeRelation::where('task_id', $id)->delete();
                $employeeData = [];
                foreach ($data['employee'] as $k => $employeeId) {
                    $employeeData[] = [
                        'task_id' => $task->id,
                        'employee_id' => $employeeId,
                    ];
                }
                if (!empty($employeeData)) {
                    TaskEmployeeRelation::insert($employeeData);
                }
            }

            if (!empty($data['task_list'])) {
                //array filter for zero empty value check
                TaskList::where('task_id', $id)->delete();
                $task_lists = $data['task_list'];
                $task_lists = !empty($task_lists) ? array_values(array_filter($task_lists)) : array();
                $listData = [];
                foreach ($task_lists as $k => $task_list) {
                    $listData[] = [
                        'task_id'   => $task->id,
                        'list_name' => $task_list,
                    ];
                }
                if (!empty($listData)) {

resources/views/admin/tasks/index.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Tasks
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Tasks</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Tasks</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    
    <!-- End Bread crumb and right sidebar toggle -->
    
    
    <!-- Container fluid  -->

    <div class="page-content container-fluid">

    @include('admin.include.alert')
        <!-- First Cards Row  -->
        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-10">
                                <h4 class="card-title">All Tasks</h4>
                            </div>
                            <div class="col-md-2 text-right">
                                <a href="{!! route('task.create') !!}" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add New</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table id="row_create_call" class="table table-striped table-hover table-bordered display" style="width:100%">
                                <thead>
                                <tr>
                                    <th width="5%">#</th>
                                    <th>Pro. Name</th>
                                    <th>Task Name</th>
                                    <th>Emp. Name</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Ratio</th>
                                    <th>Status</th>
                                    <th width="10%">Action</th>
                                </tr>
                                </thead>
                                <tbody id="tablecontents">
                                    @foreach($tasks as $key => $task)
                                    <tr class="row1" data-id="{{ $task->id }}">
                                        <td>{!! ++$key !!}</td>
                                        <td>{!! isset($task->project->project_name) ? $task->project->project_name:'' !!}</td>
                                        <td>{!! $task->name !!}</td>
                                        <td>
                                            @if(!empty($task->employees))
                                                @foreach($task->employees as $emp)
                                                    <span>{!! $emp->user->name !!} </span><br>
                                                @endforeach
                                            @endif
                                        </td>
                                        <td>{!! date('F d, Y', strtotime($task->start_date)) !!}</td>
                                        <td>{!! date('F d, Y', strtotime($task->end_date)) !!}</td>
                                        <td>{!! $task->ratio !!} Days</td>
                                        <td>
                                            @if($task->status == 'active')
                                                <span class="badge badge-pill badge-info">Active</span>
                                            @elseif($task->status == 'complete')
                                                <span class="badge badge-pill badge-success">Complete</span>
                                            @else
                                                <span class="badge badge-pill badge-danger">Deactivate</span>
                                            @endif
                                        </td>
                                        <td>
                                            <form action="{{ route('task.destroy', $task->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <a href="{!! url('taskman/task/'.$task->id) !!}" class="btn btn-success btn-circle"><i class="fa fa-eye"></i> </a>
                                                <a href="{!! url('taskman/task/'.$task->id) !!}/edit" class="btn btn-info btn-circle"><i class="fa fa-edit"></i> </a>
                                                <button type="submit" onclick="return confirm('Are you sure...?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


@endsection

@section('page_js')
    <script type="text/javascript">
        $(function () {
            $( "#tablecontents" ).sortable({
                items: "tr",
                cursor: 'move',
                opacity: 0.6,
                update: function() {
                    sendOrderToServer();
                }
            });

            function sendOrderToServer() {
                var order = [];

                $('tr.row1').each(function(index,element) {
                    order.push({
                        id: $(this).attr('data-id'),
                        position: index+1,
                    });
                });

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "{{ url('taskman/task/sortable') }}",
                    data: {
                        order:order,
                        _token: '{{csrf_token()}}'
                    },
                    success: function(response) {
                        if (response.status == "success") {
                            console.log(response);
                        } else {
                            console.log(response);
                        }
                    }
                });

            }
        });

    </script>
@endsection